### ISSUE TITLE
WCAG: Assess application manually

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/ramp-website#15]
A WCAG report on the state of compliance is updated to reflect a manual assessment of the application.

**Comment by spencerwahl** [comment]
Things found:

- 1.1.1 Non-text Content: need text alternative to pictures (alt-text w/ the descriptions for the screenshots of ramp)
- 3.1.1 Language of Page: need to alter lang attribute on `html` tag on language change.
  - RAMP needs to change language
  
On a readthrough with a screenreader and only using keyboard; 
- Main page
  - Mostly seems fine, everything on the page is reachable and nothing confusing comes up in the screenreader output
  - Keyboard controls seems to skip the "enter ramp" button so there is more to get through before getting to the next text block, can look into this
- Regular samples
  - Everything seems fine and the enter ramp/keyboard controls button shows up first (in ramp) as expected
- WET template sample
  - Much more to get through with keyboard but thats expected since theres a whole canada.ca template.
  - WET template buttons for "skip to main content" etc, might not be working correctly, should see if theres a way to fix.
  - Otherwise things seem good
